Allow svg import without width/height attributes
This is possible in an `.svg` file, as indicated by this stackexchange post [1]. I also have created them and they render just fine. Further, your code seems to already support having a `None` value for `self._height` and `self._width` so it seems that not much has to change.

Without this check, the code raises an exception. 

```
...
  File "/home/jonnyjack7/.local/lib/python3.9/site-packages/svgutils/compose.py", line 122, in __init__         
    if svg.width.endswith("%"):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

[1] https://graphicdesign.stackexchange.com/a/71574